services:
  whoami:
    image: traefik/whoami:v1.10.3
    container_name: 'whoami'
    restart: unless-stopped
    networks:
      - proxy
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.whoami.rule=Host(`${WHOAMI_TRAEFIK_HOST}`)'
      - 'traefik.http.routers.whoami.entrypoints=websecure'
      - 'traefik.http.routers.whoami.tls=true'
      - 'traefik.http.routers.whoami.tls.certresolver=dnsresolver'
      - 'traefik.http.routers.whoami.middlewares=default@file'
      - 'traefik.http.services.whoami.loadbalancer.server.port=80'

networks:
  proxy:
    external: true
