services:
  jellyfin:
    image: jellyfin/jellyfin:10
    container_name: jellyfin
    restart: unless-stopped
    networks:
      - proxy
    env_file:
      - ../../configuration/jellyfin/.env
    volumes:
      - jellyfin_config:/config
      - jellyfin_cache:/cache
      - jellyfin_media:/media
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.jellyfin.rule=Host(`${JELLYFIN_TRAEFIK_HOST}`)'
      - 'traefik.http.routers.jellyfin.entrypoints=websecure'
      - 'traefik.http.routers.jellyfin.tls=true'
      - 'traefik.http.routers.jellyfin.tls.certresolver=dnsresolver'
      - 'traefik.http.routers.jellyfin.middlewares=default@file'
      - 'traefik.http.services.jellyfin.loadbalancer.server.port=8096'

volumes:
  jellyfin_config:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${JELLYFIN_CONFIG_DIRECTORY:-./config}
  jellyfin_cache:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${JELLYFIN_CACHE_DIRECTORY:-./cache}
  jellyfin_media:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${JELLYFIN_MEDIA_DIRECTORY:-./media}

networks:
  proxy:
    external: true
