services:
  xwiki-db:
    image: postgres:17.2
    container_name: xwiki-db
    hostname: xwikidb
    restart: unless-stopped
    networks:
      - xwiki
    env_file:
      - .env
    volumes:
      - xwiki_db:/var/lib/postgresql/data

  xwiki:
    image: xwiki:16.9-postgres-tomcat
    container_name: xwiki
    restart: unless-stopped
    depends_on:
      - xwiki-db
    networks:
      - xwiki
      - proxy
    env_file:
      - ../../configuration/xwiki/.env
    volumes:
      - xwiki_data:/usr/local/xwiki
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.xwiki.rule=Host(`${XWIKI_URL}`)'
      - 'traefik.http.routers.xwiki.entrypoints=websecure'
      - 'traefik.http.routers.xwiki.tls=true'
      - 'traefik.http.routers.xwiki.tls.certresolver=dnsresolver'
      - 'traefik.http.routers.xwiki.middlewares=default@file'
      - 'traefik.http.services.xwiki.loadbalancer.server.port=8080'

volumes:
  xwiki_db:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${XWIKI_DB_DIRECTORY:-./db}
  xwiki_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${XWIKI_DATA_DIRECTORY:-./data}

networks:
  proxy:
    external: true
  xwiki:
    name: xwiki
