---
tls:
  options:
    default:
      minVersion: VersionTLS12
      cipherSuites:
        - TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
        - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
        - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305
        - TLS_AES_128_GCM_SHA256
        - TLS_AES_256_GCM_SHA384
        - TLS_CHACHA20_POLY1305_SHA256
      curvePreferences:
        - CurveP521
        - CurveP384
      sniStrict: true
http:
  middlewares:
    default:
      chain:
        middlewares:
          - autodetect
          - security
          - gzip
    auth:
      basicAuth:
        users:
          # admin:admin; must be changed for production
          - "admin:$2y$05$e2W8.2nm3ih5wCk3/r1HM.hW7vllJa14R1/hc60TUCycwiWUPsRYy"
    autodetect:
      contentType: { }
    secHeaders:
      headers:
        browserXssFilter: true
        contentTypeNosniff: true
        forceSTSHeader: true
        frameDeny: true
        stsIncludeSubdomains: true
        stsPreload: true
        stsSeconds: 31536000
        customFrameOptionsValue: "SAMEORIGIN"
        customResponseHeaders:
          # prevent exposure of too much information by removing the following headers
          server: ""
          x-powered-by: ""
    gzip:
      compress: { }
