secrets:
  netcup_customer_number:
    file: ${NETCUP_CUSTOMER_NUMBER_SECRET_PATH:-./secrets/netcup_customer_number.secret}
  netcup_api_key:
    file: ${NETCUP_API_KEY_SECRET_PATH:-./secrets/netcup_api_key.secret}
  netcup_api_password:
    file: ${NETCUP_API_PASSWORD_SECRET_PATH:-./secrets/netcup_api_password.secret}

services:
  traefik:
    image: 'traefik:v3.1'
    container_name: 'traefik'
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    secrets:
      - 'netcup_customer_number'
      - 'netcup_api_key'
      - 'netcup_api_password'
    ports:
      - '80:80'
      - '443:443'
      - '8080:8080'
    networks:
      proxy:
        ipv4_address: 172.30.255.254
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - traefik_logs:/var/log/traefik/
      - ./config/traefik.yaml:/etc/traefik/traefik.yaml:ro
      - ./config/dynamic.yaml:/etc/traefik/dynamic.yaml:ro
      - ./config/acme.json:/etc/traefik/acme.json
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.traefik.rule=Host(`traefik.change.me`)'
      - 'traefik.http.routers.traefik.entrypoints=websecure'
      - 'traefik.http.routers.traefik.tls=true'
      - 'traefik.http.routers.traefik.tls.certresolver=dnsresolver'
      - 'traefik.http.routers.traefik.middlewares=auth@file,default@file'
      - 'traefik.http.routers.traefik.service=api@internal'

  whoami:
    image: 'traefik/whoami'
    container_name: 'whoami'
    restart: unless-stopped
    networks:
      - proxy
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.whoami.rule=Host(`whoami.change.me`)'
      - 'traefik.http.routers.whoami.entrypoints=websecure'
      - 'traefik.http.routers.whoami.tls=true'
      - 'traefik.http.routers.whoami.tls.certresolver=dnsresolver'
      - 'traefik.http.routers.whoami.middlewares=default@file'
      - 'traefik.http.services.whoami.loadbalancer.server.port=80'

volumes:
  traefik_logs:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${TRAEFIK_LOGS_DIRECTORY:-./logs}

networks:
  proxy:
    driver: bridge
    ipam:
      config:
        - subnet: '172.30.0.0/16'
