services:
  traefik:
    image: 'traefik:v3.2.1'
    container_name: 'traefik'
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    ports:
      - '80:80'
      - '443:443'
      - '8080:8080'
    networks:
      proxy:
        ipv4_address: 172.30.255.254
    env_file:
      - ../../configuration/traefik/.env
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - traefik_logs:/var/log/traefik/
      - ./config/traefik.yml:/etc/traefik/traefik.yml:ro
      - ./config/dynamic.yml:/etc/traefik/dynamic.yml:ro
      - ./config/acme.json:/etc/traefik/acme.json
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.traefik.rule=Host(`${TRAEFIK_HOST}`)'
      - 'traefik.http.routers.traefik.entrypoints=websecure'
      - 'traefik.http.routers.traefik.tls=true'
      - 'traefik.http.routers.traefik.tls.certresolver=dnsresolver'
      - 'traefik.http.routers.traefik.middlewares=auth@file,default@file'
      - 'traefik.http.routers.traefik.service=api@internal'

volumes:
  traefik_logs:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${TRAEFIK_LOGS_DIRECTORY:-./logs}

networks:
  proxy:
    name: proxy
    driver: bridge
    ipam:
      config:
        - subnet: '172.30.0.0/16'
